<a href="https://colab.research.google.com/github/Reji20/Datascience--lab/blob/main/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [ ]:
df=pd.read_csv("/content/seeds.csv") 
df.head()

15.26  14.84   0.871  5.763  3.312  2.221   5.22  1
0  14.88  14.57  0.8811  5.554  3.333  1.018  4.956  1
1  14.29  14.09  0.9050  5.291  3.337  2.699  4.825  1
2  13.84  13.94  0.8955  5.324  3.379  2.259  4.805  1
3  16.14  14.99  0.9034  5.658  3.562  1.355  5.175  1
4  14.38  14.21  0.8951  5.386  3.312  2.462  4.956  1

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.40,random_state=None)

In [ ]:
gnb=GaussianNB()
gnb.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred=gnb.predict(x_test)
y_pred

array([2, 1, 1, 3, 1, 1, 1, 1, 3, 2, 3, 1, 3, 3, 1, 3, 2, 1, 1, 3, 1, 2,
       2, 1, 3, 2, 1, 2, 2, 3, 1, 2, 3, 3, 2, 3, 1, 3, 2, 1, 3, 2, 2, 1,
       1, 3, 3, 1, 3, 3, 3, 1, 3, 2, 2, 2, 1, 1, 3, 2, 1, 2, 3, 3, 3, 3,
       3, 3, 1, 3, 2, 1, 2, 3, 1, 2, 3, 3, 2, 2, 3, 2, 1, 1])

In [ ]:
print(metrics.accuracy_score(y_test,y_pred))

0.8452380952380952


In [ ]:
print(metrics.confusion_matrix(y_test,y_pred))

[[20  1  4]
 [ 6 23  0]
 [ 2  0 28]]
